# Generated by Django 4.2.2 on 2023-06-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_profile_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='accounts',
        ),
    ]
